### ISSUE TITLE
Add `python-sympy` as dependency(?)

### ISSUE THREAD

**Issue by dreirund** [jzbor/sdiff-gtk#7]
If I understand [`pyproject.toml`](https://github.com/jzbor/sdiff-gtk/blob/master/pyproject.toml) correctly (I don't know how python dependency tracking works), then `sympy` needs to be added:

As reported [&nearr;&hairsp;here](https://aur.archlinux.org/packages/sdiff-gtk#comment-906364), it seems to be a needed runtime dependency.

Regards!

**Comment by jzbor** [comment]
Have you tried it with the PyTorch version defined in the `pyproject.toml`. Your report in the AUR seems like a PyTorch issue to be honest. The error stems from the import of torch itsself, not from a call to `sympy`.

**Comment by dreirund** [comment]
> Your report in the AUR seems like a PyTorch issue to be honest. The error stems from the import of torch itsself, not from a call to `sympy`.

You are right, I made it a [&nearr;&hairsp;bug report to Arch Linux package `python-pytorch`](https://bugs.archlinux.org/task/77895).
